# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sheetGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SheetWindow(object):
    def setupUi(self, SheetWindow):
        SheetWindow.setObjectName("SheetWindow")
        SheetWindow.resize(379, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/windowIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SheetWindow.setWindowIcon(icon)
        SheetWindow.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.centralwidget = QtWidgets.QWidget(SheetWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("border:No;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 344, 1465))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_12.addWidget(self.label_26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_13.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_13.addWidget(self.label_28)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_19.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_19.addWidget(self.label_41)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_5.addWidget(self.label_39)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_37.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_18.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_18.addWidget(self.label_38)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_17.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_17.addWidget(self.label_36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_16.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_16.addWidget(self.label_34)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_15.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_15.addWidget(self.label_32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_14.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_14.addWidget(self.label_30)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_20.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_20.addWidget(self.label_43)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_59.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_28.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_28.addWidget(self.label_60)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_58.setObjectName("label_58")
        self.verticalLayout_6.addWidget(self.label_58)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_6.addWidget(self.line_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_56.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_27.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_27.addWidget(self.label_57)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_54.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_26.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_26.addWidget(self.label_55)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_52.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_25.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_25.addWidget(self.label_53)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_50.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_24.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_24.addWidget(self.label_51)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_48.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_23.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_23.addWidget(self.label_49)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_22.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_22.addWidget(self.label_47)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_21.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_21.addWidget(self.label_45)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_63.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_30.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_30.addWidget(self.label_64)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_61.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_29.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_29.addWidget(self.label_62)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_75 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_75.setObjectName("label_75")
        self.verticalLayout_7.addWidget(self.label_75)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_82.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_82.setObjectName("label_82")
        self.horizontalLayout_39.addWidget(self.label_82)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_39.addWidget(self.label_83)
        self.verticalLayout_2.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_73.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_35.addWidget(self.label_73)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_35.addWidget(self.label_74)
        self.verticalLayout_2.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_71.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_34.addWidget(self.label_71)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_34.addWidget(self.label_72)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_69.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_33.addWidget(self.label_69)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_33.addWidget(self.label_70)
        self.verticalLayout_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_32.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_32.addWidget(self.label_68)
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_65.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_31.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_31.addWidget(self.label_66)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_76 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_76.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_36.addWidget(self.label_76)
        self.label_77 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_36.addWidget(self.label_77)
        self.verticalLayout_2.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_78.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_37.addWidget(self.label_78)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_37.addWidget(self.label_79)
        self.verticalLayout_2.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_80.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_38.addWidget(self.label_80)
        self.label_81 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_38.addWidget(self.label_81)
        self.verticalLayout_2.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_86.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_86.setObjectName("label_86")
        self.horizontalLayout_41.addWidget(self.label_86)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_41.addWidget(self.label_87)
        self.verticalLayout_2.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_84.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_84.setObjectName("label_84")
        self.horizontalLayout_40.addWidget(self.label_84)
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_40.addWidget(self.label_85)
        self.verticalLayout_2.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_103 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_103.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_103.setObjectName("label_103")
        self.horizontalLayout_49.addWidget(self.label_103)
        self.label_104 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_104.setObjectName("label_104")
        self.horizontalLayout_49.addWidget(self.label_104)
        self.verticalLayout_2.addLayout(self.horizontalLayout_49)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_102 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_102.setFont(font)
        self.label_102.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_102.setObjectName("label_102")
        self.verticalLayout_8.addWidget(self.label_102)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_8.addWidget(self.line_8)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_100 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_100.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_100.setObjectName("label_100")
        self.horizontalLayout_48.addWidget(self.label_100)
        self.label_101 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_101.setObjectName("label_101")
        self.horizontalLayout_48.addWidget(self.label_101)
        self.verticalLayout_2.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_98 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_98.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_98.setObjectName("label_98")
        self.horizontalLayout_47.addWidget(self.label_98)
        self.label_99 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_99.setObjectName("label_99")
        self.horizontalLayout_47.addWidget(self.label_99)
        self.verticalLayout_2.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_96 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_96.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_46.addWidget(self.label_96)
        self.label_97 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_97.setObjectName("label_97")
        self.horizontalLayout_46.addWidget(self.label_97)
        self.verticalLayout_2.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_94 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_94.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_45.addWidget(self.label_94)
        self.label_95 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_45.addWidget(self.label_95)
        self.verticalLayout_2.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_92 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_92.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_44.addWidget(self.label_92)
        self.label_93 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_93.setObjectName("label_93")
        self.horizontalLayout_44.addWidget(self.label_93)
        self.verticalLayout_2.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_90 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_90.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_43.addWidget(self.label_90)
        self.label_91 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_43.addWidget(self.label_91)
        self.verticalLayout_2.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_88 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_88.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_42.addWidget(self.label_88)
        self.label_89 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout_42.addWidget(self.label_89)
        self.verticalLayout_2.addLayout(self.horizontalLayout_42)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_115 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_115.setFont(font)
        self.label_115.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_115.setObjectName("label_115")
        self.verticalLayout_9.addWidget(self.label_115)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_9.addWidget(self.line_9)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_113 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_113.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_113.setObjectName("label_113")
        self.horizontalLayout_54.addWidget(self.label_113)
        self.label_114 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_114.setObjectName("label_114")
        self.horizontalLayout_54.addWidget(self.label_114)
        self.verticalLayout_2.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_111 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_111.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_111.setObjectName("label_111")
        self.horizontalLayout_53.addWidget(self.label_111)
        self.label_112 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_112.setObjectName("label_112")
        self.horizontalLayout_53.addWidget(self.label_112)
        self.verticalLayout_2.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_109 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_109.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_109.setObjectName("label_109")
        self.horizontalLayout_52.addWidget(self.label_109)
        self.label_110 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_110.setObjectName("label_110")
        self.horizontalLayout_52.addWidget(self.label_110)
        self.verticalLayout_2.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_107 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_107.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_107.setObjectName("label_107")
        self.horizontalLayout_51.addWidget(self.label_107)
        self.label_108 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_108.setObjectName("label_108")
        self.horizontalLayout_51.addWidget(self.label_108)
        self.verticalLayout_2.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_105 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_105.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_105.setObjectName("label_105")
        self.horizontalLayout_50.addWidget(self.label_105)
        self.label_106 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_106.setObjectName("label_106")
        self.horizontalLayout_50.addWidget(self.label_106)
        self.verticalLayout_2.addLayout(self.horizontalLayout_50)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_118 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_118.setFont(font)
        self.label_118.setStyleSheet("min-height:15;\n"
"max-height:15;\n"
"background-color: rgba(0, 0, 0, 0%);")
        self.label_118.setObjectName("label_118")
        self.verticalLayout_10.addWidget(self.label_118)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setStyleSheet("background-color:rgb(255, 85, 0);\n"
"border:No;\n"
"height:1px")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_10.addWidget(self.line_10)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_116 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_116.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_116.setObjectName("label_116")
        self.horizontalLayout_55.addWidget(self.label_116)
        self.label_117 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_117.setObjectName("label_117")
        self.horizontalLayout_55.addWidget(self.label_117)
        self.verticalLayout_2.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_121 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_121.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_121.setObjectName("label_121")
        self.horizontalLayout_57.addWidget(self.label_121)
        self.label_122 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_122.setObjectName("label_122")
        self.horizontalLayout_57.addWidget(self.label_122)
        self.verticalLayout_2.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_119 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_119.setStyleSheet("min-width:100px;\n"
"max-width:100px;")
        self.label_119.setObjectName("label_119")
        self.horizontalLayout_56.addWidget(self.label_119)
        self.label_120 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_120.setObjectName("label_120")
        self.horizontalLayout_56.addWidget(self.label_120)
        self.verticalLayout_2.addLayout(self.horizontalLayout_56)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        SheetWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SheetWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 379, 21))
        self.menubar.setObjectName("menubar")
        SheetWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SheetWindow)
        self.statusbar.setObjectName("statusbar")
        SheetWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SheetWindow)
        QtCore.QMetaObject.connectSlotsByName(SheetWindow)

    def retranslateUi(self, SheetWindow):
        _translate = QtCore.QCoreApplication.translate
        SheetWindow.setWindowTitle(_translate("SheetWindow", "PyRex Regex Sheet"))
        self.label_3.setText(_translate("SheetWindow", "Regular Expression Basics"))
        self.label.setText(_translate("SheetWindow", "."))
        self.label_2.setText(_translate("SheetWindow", "Any character except newline"))
        self.label_5.setText(_translate("SheetWindow", "a"))
        self.label_6.setText(_translate("SheetWindow", "The character a"))
        self.label_7.setText(_translate("SheetWindow", "ab"))
        self.label_8.setText(_translate("SheetWindow", "The string ab"))
        self.label_13.setText(_translate("SheetWindow", "a|b"))
        self.label_14.setText(_translate("SheetWindow", "a or b"))
        self.label_11.setText(_translate("SheetWindow", "a*"))
        self.label_12.setText(_translate("SheetWindow", "0 or more a\'s"))
        self.label_9.setText(_translate("SheetWindow", "\\"))
        self.label_10.setText(_translate("SheetWindow", "Escapes a special character"))
        self.label_4.setText(_translate("SheetWindow", "Regular Expression Quantifiers"))
        self.label_25.setText(_translate("SheetWindow", "*"))
        self.label_26.setText(_translate("SheetWindow", "0 or more"))
        self.label_23.setText(_translate("SheetWindow", "+"))
        self.label_24.setText(_translate("SheetWindow", "1 or more"))
        self.label_21.setText(_translate("SheetWindow", "?"))
        self.label_22.setText(_translate("SheetWindow", "0 or 1"))
        self.label_19.setText(_translate("SheetWindow", "{2}"))
        self.label_20.setText(_translate("SheetWindow", "Exactly 2"))
        self.label_17.setText(_translate("SheetWindow", "{2, 5}"))
        self.label_18.setText(_translate("SheetWindow", "Between 2 and 5"))
        self.label_15.setText(_translate("SheetWindow", "{2,}"))
        self.label_16.setText(_translate("SheetWindow", "2 or more"))
        self.label_27.setText(_translate("SheetWindow", "{,5}"))
        self.label_28.setText(_translate("SheetWindow", "Up to 5"))
        self.label_40.setText(_translate("SheetWindow", "ab"))
        self.label_41.setText(_translate("SheetWindow", "The string ab"))
        self.label_39.setText(_translate("SheetWindow", "Regular Expression Groups"))
        self.label_37.setText(_translate("SheetWindow", "(...)"))
        self.label_38.setText(_translate("SheetWindow", "Capturing group"))
        self.label_35.setText(_translate("SheetWindow", "(?P<Y>...)"))
        self.label_36.setText(_translate("SheetWindow", "Capturing group named Y"))
        self.label_33.setText(_translate("SheetWindow", "(?:...)"))
        self.label_34.setText(_translate("SheetWindow", "Non-capturing group"))
        self.label_31.setText(_translate("SheetWindow", "\\Y"))
        self.label_32.setText(_translate("SheetWindow", "Match the Y\'th captured group"))
        self.label_29.setText(_translate("SheetWindow", "(?P=Y)"))
        self.label_30.setText(_translate("SheetWindow", "Match the named group Y"))
        self.label_42.setText(_translate("SheetWindow", "(?#...)"))
        self.label_43.setText(_translate("SheetWindow", "Comment"))
        self.label_59.setText(_translate("SheetWindow", "{2}"))
        self.label_60.setText(_translate("SheetWindow", "Exactly 2"))
        self.label_58.setText(_translate("SheetWindow", "Regular Expression Character Classes"))
        self.label_56.setText(_translate("SheetWindow", "[ab-d]"))
        self.label_57.setText(_translate("SheetWindow", "One character of: a, b, c, d"))
        self.label_54.setText(_translate("SheetWindow", "[^ab-d]"))
        self.label_55.setText(_translate("SheetWindow", "One character except: a, b, c, d"))
        self.label_52.setText(_translate("SheetWindow", "[b]"))
        self.label_53.setText(_translate("SheetWindow", "Backspace character"))
        self.label_50.setText(_translate("SheetWindow", "\\d"))
        self.label_51.setText(_translate("SheetWindow", "One digit"))
        self.label_48.setText(_translate("SheetWindow", "\\D"))
        self.label_49.setText(_translate("SheetWindow", "One non-digit"))
        self.label_46.setText(_translate("SheetWindow", "\\s"))
        self.label_47.setText(_translate("SheetWindow", "One whitespace"))
        self.label_44.setText(_translate("SheetWindow", "\\S"))
        self.label_45.setText(_translate("SheetWindow", "One non-whitespace"))
        self.label_63.setText(_translate("SheetWindow", "\\w"))
        self.label_64.setText(_translate("SheetWindow", "One word character"))
        self.label_61.setText(_translate("SheetWindow", "\\W"))
        self.label_62.setText(_translate("SheetWindow", "One non-word character"))
        self.label_75.setText(_translate("SheetWindow", "Regular Expression Assertions"))
        self.label_82.setText(_translate("SheetWindow", "^"))
        self.label_83.setText(_translate("SheetWindow", "Start of string"))
        self.label_73.setText(_translate("SheetWindow", "\\A"))
        self.label_74.setText(_translate("SheetWindow", "Start of string, ignores m flag"))
        self.label_71.setText(_translate("SheetWindow", "$"))
        self.label_72.setText(_translate("SheetWindow", "End of string"))
        self.label_69.setText(_translate("SheetWindow", "\\Z"))
        self.label_70.setText(_translate("SheetWindow", "End of string, ignores m flag"))
        self.label_67.setText(_translate("SheetWindow", "\\b"))
        self.label_68.setText(_translate("SheetWindow", "Word boundary"))
        self.label_65.setText(_translate("SheetWindow", "\\B"))
        self.label_66.setText(_translate("SheetWindow", "Non-word boundary"))
        self.label_76.setText(_translate("SheetWindow", "(?=...)"))
        self.label_77.setText(_translate("SheetWindow", "Positive lookahead"))
        self.label_78.setText(_translate("SheetWindow", "(?!...)"))
        self.label_79.setText(_translate("SheetWindow", "Negative lookahead"))
        self.label_80.setText(_translate("SheetWindow", "(?<=...)"))
        self.label_81.setText(_translate("SheetWindow", "Positive lookbehind"))
        self.label_86.setText(_translate("SheetWindow", "(?<!...)"))
        self.label_87.setText(_translate("SheetWindow", "Negative lookbehind"))
        self.label_84.setText(_translate("SheetWindow", "(?()|)"))
        self.label_85.setText(_translate("SheetWindow", "Conditional"))
        self.label_103.setText(_translate("SheetWindow", "\\Z"))
        self.label_104.setText(_translate("SheetWindow", "End of string, ignores m flag"))
        self.label_102.setText(_translate("SheetWindow", "Regular Expression Flags"))
        self.label_100.setText(_translate("SheetWindow", "i"))
        self.label_101.setText(_translate("SheetWindow", "Ignore case"))
        self.label_98.setText(_translate("SheetWindow", "m"))
        self.label_99.setText(_translate("SheetWindow", "^ and $ match start and end of line"))
        self.label_96.setText(_translate("SheetWindow", "s"))
        self.label_97.setText(_translate("SheetWindow", "Matches newline as well"))
        self.label_94.setText(_translate("SheetWindow", "x"))
        self.label_95.setText(_translate("SheetWindow", "Allow spaces and comments"))
        self.label_92.setText(_translate("SheetWindow", "L"))
        self.label_93.setText(_translate("SheetWindow", "Locale character classes"))
        self.label_90.setText(_translate("SheetWindow", "u"))
        self.label_91.setText(_translate("SheetWindow", "Unicode character classes"))
        self.label_88.setText(_translate("SheetWindow", "(?iLmsux)"))
        self.label_89.setText(_translate("SheetWindow", "Set flags within regex"))
        self.label_115.setText(_translate("SheetWindow", "Regular Expression Flags"))
        self.label_113.setText(_translate("SheetWindow", "\\n"))
        self.label_114.setText(_translate("SheetWindow", "Newline"))
        self.label_111.setText(_translate("SheetWindow", "\\r"))
        self.label_112.setText(_translate("SheetWindow", "Carriage return"))
        self.label_109.setText(_translate("SheetWindow", "\\t"))
        self.label_110.setText(_translate("SheetWindow", "Tab"))
        self.label_107.setText(_translate("SheetWindow", "\\YYY"))
        self.label_108.setText(_translate("SheetWindow", "Octal character YYY"))
        self.label_105.setText(_translate("SheetWindow", "\\xYY"))
        self.label_106.setText(_translate("SheetWindow", "Hexadecimal character YY"))
        self.label_118.setText(_translate("SheetWindow", "Regular Expression Replacement"))
        self.label_116.setText(_translate("SheetWindow", "\\g<0>"))
        self.label_117.setText(_translate("SheetWindow", "Insert entire match"))
        self.label_121.setText(_translate("SheetWindow", "\\g<Y>"))
        self.label_122.setText(_translate("SheetWindow", "Insert match Y (name or number)"))
        self.label_119.setText(_translate("SheetWindow", "\\Y"))
        self.label_120.setText(_translate("SheetWindow", "Insert group numbered Y"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SheetWindow = QtWidgets.QMainWindow()
    ui = Ui_SheetWindow()
    ui.setupUi(SheetWindow)
    SheetWindow.show()
    sys.exit(app.exec_())
